### ISSUE TITLE
Speedup over word2vec or fasttext (without subword: -maxn 0)

### ISSUE THREAD

**Issue by saurabh3949** [IntelLabs/pWord2Vec#2]
Hi,
If I run pword2vec with streaming from disk enabled, it performs slower than word2vec or fastText. Is the speedup primarily because of loading data into memory?

**Comment by shihaoji** [comment]
No. Please see the paper for more details.

On single machine and multi machine settings, we didn't see more than 5% speed difference between streaming from disk and memory. Of course, all our experiments were done on CPU servers. 

What are your hardware specs?

**Comment by saurabh3949** [comment]
Thanks for your reply @shihaoji . I was compiling using g++ and forgot to use the O3 flag. Its definitely much faster than fastText 👍

**Comment by shihaoji** [comment]
Good to hear of this!

BTW, if you can use Intel compiler, that will bring you even more speed ups.  and free copies of Intel compiler can be found at https://software.intel.com/en-us/qualify-for-free-software

**Comment by shivam05011996** [comment]
Hi @saurabh3949 ,
I would like to know what changes you made so that you can use gcc compiler. I would like do a performance test against word2vec, and fasttext.
Thank You.
